#!/bin/bash

DOCKERINIT_CONFIG_DIR=${DOCKERINIT_CONFIG_DIR:-/etc/docker-init}

if [[ ${DOCKERINIT_DEBUG} -gt 0 ]]; then
  echo -e "Debug run requested.\n"
  echo -e "Configuration directory: ${DOCKERINIT_CONFIG_DIR}\n"
  echo -ne "run-parts --list:\n"
  run-parts --list -- ${DOCKERINIT_CONFIG_DIR}/init.d
  echo -ne "\n"
  echo -ne "run-parts --test:\n"
  run-parts --test -- ${DOCKERINIT_CONFIG_DIR}/init.d
  echo -ne "\n"
fi

run-parts --exit-on-error --lsbsysinit --verbose -- ${DOCKERINIT_CONFIG_DIR}/init.d

exec ${*}
